//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.ResubmitProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentLog
    {
        public int DocumentLogId { get; set; }
        public string DocumentLogName { get; set; }
        public long DocumentObjectId { get; set; }
        public int MessageLogId { get; set; }
        public int DocumentMapId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int LastModifiedById { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual DocumentMap DocumentMap { get; set; }
        public virtual MessageLog MessageLog { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
