//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.ResubmitProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionQueueLog
    {
        public int Id { get; set; }
        public int ExceptionGroupId { get; set; }
        public int QueueCount { get; set; }
        public int ArchiveCount { get; set; }
        public int NewCount { get; set; }
        public int ActiveCount { get; set; }
        public int HoldCount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Tenantid { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
