//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.ResubmitProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FASTTaskMap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FASTTaskMap()
        {
            this.FASTWorkflowMaps = new HashSet<FASTWorkflowMap>();
        }
    
        public int FASTTaskMapId { get; set; }
        public string FASTTaskMapName { get; set; }
        public int MessageTypeId { get; set; }
        public int TypeCodeId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public int ServiceId { get; set; }
        public string FASTTaskMapDesc { get; set; }
        public bool IsInbound { get; set; }
        public bool ContainsReasonCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int LastModifiedById { get; set; }
        public int TenantId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual MessageType MessageType { get; set; }
        public virtual Service Service { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual TypeCode TypeCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FASTWorkflowMap> FASTWorkflowMaps { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
