//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.ResubmitProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FASTFileNumber
    {
        public int RegionId { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public Nullable<long> LastUsedNumber { get; set; }
    }
}
