//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.BEQRejectProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentObjectMetadata
    {
        public int Id { get; set; }
        public long DocumentObjectId { get; set; }
        public string ExternalRefNumber { get; set; }
        public string CustomerRefNumber { get; set; }
        public string InternalRefNumber { get; set; }
        public Nullable<int> InternalRefId { get; set; }
        public string Source { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string LocationExternalId { get; set; }
        public string ProviderExternalId { get; set; }
        public Nullable<int> ServiceRequestId { get; set; }
        public string BuyerName { get; set; }
        public string TransactionType { get; set; }
        public string ProgramTypeName { get; set; }
        public Nullable<int> ExternalApplicationId { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public string MessageType { get; set; }
        public Nullable<bool> HasDocument { get; set; }
        public string DocumentName { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> EscrowOfficeId { get; set; }
    }
}
