//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.BEQRejectProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FASTPreferenceProduct
    {
        public int FASTPreferenceProductId { get; set; }
        public int FASTPreferenceMapId { get; set; }
        public int ProductId { get; set; }
    
        public virtual FASTPreferenceMap FASTPreferenceMap { get; set; }
        public virtual Product Product { get; set; }
    }
}
