//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.BEQRejectProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageMap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MessageMap()
        {
            this.DocumentMessageMaps = new HashSet<DocumentMessageMap>();
            this.MessageLogs = new HashSet<MessageLog>();
        }
    
        public int MessageMapId { get; set; }
        public int MessageTypeId { get; set; }
        public int ExternalMessageTypeId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public bool IsInbound { get; set; }
        public Nullable<short> Sequence { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int LastModifiedById { get; set; }
        public int TenantId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentMessageMap> DocumentMessageMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageLog> MessageLogs { get; set; }
        public virtual MessageType MessageType { get; set; }
        public virtual MessageType MessageType1 { get; set; }
        public virtual Service Service { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
