//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.BEQRejectProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRequest()
        {
            this.MessageLogs = new HashSet<MessageLog>();
            this.RealECExtensions = new HashSet<RealECExtension>();
            this.ServiceRequestInfoes = new HashSet<ServiceRequestInfo>();
        }
    
        public int ServiceRequestId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public int ApplicationId { get; set; }
        public string ExternalRefNum { get; set; }
        public string CustomerRefNum { get; set; }
        public string InternalRefNum { get; set; }
        public Nullable<int> InternalRefId { get; set; }
        public int ServiceId { get; set; }
        public int ProviderId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedById { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<bool> HasSLA { get; set; }
        public Nullable<int> StatusTypeCodeId { get; set; }
        public Nullable<bool> IsFileCreated { get; set; }
        public Nullable<int> InternalApplicationId { get; set; }
        public string Custom { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageLog> MessageLogs { get; set; }
        public virtual Provider Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RealECExtension> RealECExtensions { get; set; }
        public virtual Service Service { get; set; }
        public virtual Tenant Tenant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestInfo> ServiceRequestInfoes { get; set; }
        public virtual Application Application1 { get; set; }
    }
}
