//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.BEQRejectProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLAMonitor
    {
        public int SLAMonitorId { get; set; }
        public int ServiceRequestId { get; set; }
        public int SLAPreferenceTypeCode { get; set; }
        public string SLAPreferenceValue { get; set; }
        public bool IsCompleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int LastModifiedById { get; set; }
        public int TenantId { get; set; }
        public bool InProgress { get; set; }
    }
}
