//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.BEQRejectProcess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TerminalEntities : DbContext
    {
        public TerminalEntities()
            : base("name=TerminalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicationHeartbeat> ApplicationHeartbeats { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Credential> Credentials { get; set; }
        public virtual DbSet<CredentialEndPoint> CredentialEndPoints { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerInfo> CustomerInfoes { get; set; }
        public virtual DbSet<DocumentLog> DocumentLogs { get; set; }
        public virtual DbSet<DocumentMap> DocumentMaps { get; set; }
        public virtual DbSet<DocumentMessageMap> DocumentMessageMaps { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<Exception> Exceptions { get; set; }
        public virtual DbSet<ExceptionNote> ExceptionNotes { get; set; }
        public virtual DbSet<ExceptionType> ExceptionTypes { get; set; }
        public virtual DbSet<FASTApplicationMap> FASTApplicationMaps { get; set; }
        public virtual DbSet<FASTBusinessProgramType> FASTBusinessProgramTypes { get; set; }
        public virtual DbSet<FASTContactMap> FASTContactMaps { get; set; }
        public virtual DbSet<FASTFileNumber> FASTFileNumbers { get; set; }
        public virtual DbSet<FASTGABMap> FASTGABMaps { get; set; }
        public virtual DbSet<FASTOffice> FASTOffices { get; set; }
        public virtual DbSet<FASTOfficeMap> FASTOfficeMaps { get; set; }
        public virtual DbSet<FASTPreferenceBusinessProgram> FASTPreferenceBusinessPrograms { get; set; }
        public virtual DbSet<FASTPreferenceMap> FASTPreferenceMaps { get; set; }
        public virtual DbSet<FASTPreferenceProduct> FASTPreferenceProducts { get; set; }
        public virtual DbSet<FASTProgramType> FASTProgramTypes { get; set; }
        public virtual DbSet<FASTRegion> FASTRegions { get; set; }
        public virtual DbSet<FASTSearchType> FASTSearchTypes { get; set; }
        public virtual DbSet<FASTWorkflowMap> FASTWorkflowMaps { get; set; }
        public virtual DbSet<GABLocationCondition> GABLocationConditions { get; set; }
        public virtual DbSet<LoanCondition> LoanConditions { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationCondition> LocationConditions { get; set; }
        public virtual DbSet<LookupMap> LookupMaps { get; set; }
        public virtual DbSet<MessageLog> MessageLogs { get; set; }
        public virtual DbSet<MessageMap> MessageMaps { get; set; }
        public virtual DbSet<MessageType> MessageTypes { get; set; }
        public virtual DbSet<OfficeLocationCondition> OfficeLocationConditions { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductCondition> ProductConditions { get; set; }
        public virtual DbSet<ProductMap> ProductMaps { get; set; }
        public virtual DbSet<ProductProviderMap> ProductProviderMaps { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<RealECExtension> RealECExtensions { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceRequest> ServiceRequests { get; set; }
        public virtual DbSet<ServiceRequestInfo> ServiceRequestInfoes { get; set; }
        public virtual DbSet<SLAMonitor> SLAMonitors { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
        public virtual DbSet<Tower_Roles> Tower_Roles { get; set; }
        public virtual DbSet<Tower_UserClaims> Tower_UserClaims { get; set; }
        public virtual DbSet<Tower_Users> Tower_Users { get; set; }
        public virtual DbSet<TypeCode> TypeCodes { get; set; }
        public virtual DbSet<WinscapeLocation> WinscapeLocations { get; set; }
        public virtual DbSet<WinscapePipeline> WinscapePipelines { get; set; }
        public virtual DbSet<BEQRegionRetention> BEQRegionRetentions { get; set; }
    
        public virtual ObjectResult<GetApplicationHeartbeat_Result> GetApplicationHeartbeat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetApplicationHeartbeat_Result>("GetApplicationHeartbeat");
        }
    
        public virtual ObjectResult<string> GetDependancyRecordOutput(Nullable<int> id, string iNtablename)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var iNtablenameParameter = iNtablename != null ?
                new ObjectParameter("INtablename", iNtablename) :
                new ObjectParameter("INtablename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetDependancyRecordOutput", idParameter, iNtablenameParameter);
        }
    
        public virtual ObjectResult<GetExceptionInfo_Result> GetExceptionInfo(Nullable<System.DateTime> startdate, Nullable<System.DateTime> enddate, Nullable<int> exceptiongroupid, Nullable<int> tenantId, Nullable<bool> isincluderesolved, string exceptionTypeName)
        {
            var startdateParameter = startdate.HasValue ?
                new ObjectParameter("startdate", startdate) :
                new ObjectParameter("startdate", typeof(System.DateTime));
    
            var enddateParameter = enddate.HasValue ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(System.DateTime));
    
            var exceptiongroupidParameter = exceptiongroupid.HasValue ?
                new ObjectParameter("exceptiongroupid", exceptiongroupid) :
                new ObjectParameter("exceptiongroupid", typeof(int));
    
            var tenantIdParameter = tenantId.HasValue ?
                new ObjectParameter("tenantId", tenantId) :
                new ObjectParameter("tenantId", typeof(int));
    
            var isincluderesolvedParameter = isincluderesolved.HasValue ?
                new ObjectParameter("isincluderesolved", isincluderesolved) :
                new ObjectParameter("isincluderesolved", typeof(bool));
    
            var exceptionTypeNameParameter = exceptionTypeName != null ?
                new ObjectParameter("exceptionTypeName", exceptionTypeName) :
                new ObjectParameter("exceptionTypeName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetExceptionInfo_Result>("GetExceptionInfo", startdateParameter, enddateParameter, exceptiongroupidParameter, tenantIdParameter, isincluderesolvedParameter, exceptionTypeNameParameter);
        }
    
        public virtual int GetExceptionQueueLog(Nullable<int> exgroupid, Nullable<int> tenantId)
        {
            var exgroupidParameter = exgroupid.HasValue ?
                new ObjectParameter("exgroupid", exgroupid) :
                new ObjectParameter("exgroupid", typeof(int));
    
            var tenantIdParameter = tenantId.HasValue ?
                new ObjectParameter("tenantId", tenantId) :
                new ObjectParameter("tenantId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetExceptionQueueLog", exgroupidParameter, tenantIdParameter);
        }
    
        public virtual ObjectResult<GetFASTOfficeMapList_Result> GetFASTOfficeMapList(string contactId, Nullable<int> providerId, Nullable<int> locationId, string state, string county, Nullable<int> tenantId)
        {
            var contactIdParameter = contactId != null ?
                new ObjectParameter("contactId", contactId) :
                new ObjectParameter("contactId", typeof(string));
    
            var providerIdParameter = providerId.HasValue ?
                new ObjectParameter("providerId", providerId) :
                new ObjectParameter("providerId", typeof(int));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("locationId", locationId) :
                new ObjectParameter("locationId", typeof(int));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var countyParameter = county != null ?
                new ObjectParameter("county", county) :
                new ObjectParameter("county", typeof(string));
    
            var tenantIdParameter = tenantId.HasValue ?
                new ObjectParameter("tenantId", tenantId) :
                new ObjectParameter("tenantId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFASTOfficeMapList_Result>("GetFASTOfficeMapList", contactIdParameter, providerIdParameter, locationIdParameter, stateParameter, countyParameter, tenantIdParameter);
        }
    
        public virtual ObjectResult<GetProductList_Result> GetProductList(string contactId, Nullable<int> providerId, Nullable<int> locationId, Nullable<int> tenantId, Nullable<int> applicationid)
        {
            var contactIdParameter = contactId != null ?
                new ObjectParameter("contactId", contactId) :
                new ObjectParameter("contactId", typeof(string));
    
            var providerIdParameter = providerId.HasValue ?
                new ObjectParameter("providerId", providerId) :
                new ObjectParameter("providerId", typeof(int));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("locationId", locationId) :
                new ObjectParameter("locationId", typeof(int));
    
            var tenantIdParameter = tenantId.HasValue ?
                new ObjectParameter("tenantId", tenantId) :
                new ObjectParameter("tenantId", typeof(int));
    
            var applicationidParameter = applicationid.HasValue ?
                new ObjectParameter("applicationid", applicationid) :
                new ObjectParameter("applicationid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductList_Result>("GetProductList", contactIdParameter, providerIdParameter, locationIdParameter, tenantIdParameter, applicationidParameter);
        }
    
        public virtual ObjectResult<GetFASTOfficeMap_Result> GetFASTOfficeMap(Nullable<int> providerId, Nullable<int> locationId, string state, string county, Nullable<int> customerid, Nullable<int> contactid)
        {
            var providerIdParameter = providerId.HasValue ?
                new ObjectParameter("providerId", providerId) :
                new ObjectParameter("providerId", typeof(int));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("locationId", locationId) :
                new ObjectParameter("locationId", typeof(int));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var countyParameter = county != null ?
                new ObjectParameter("county", county) :
                new ObjectParameter("county", typeof(string));
    
            var customeridParameter = customerid.HasValue ?
                new ObjectParameter("customerid", customerid) :
                new ObjectParameter("customerid", typeof(int));
    
            var contactidParameter = contactid.HasValue ?
                new ObjectParameter("contactid", contactid) :
                new ObjectParameter("contactid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFASTOfficeMap_Result>("GetFASTOfficeMap", providerIdParameter, locationIdParameter, stateParameter, countyParameter, customeridParameter, contactidParameter);
        }
    }
}
