//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.ExceptionQueueSnapshot
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TerminalEntities : DbContext
    {
        public TerminalEntities()
            : base("name=TerminalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exception> Exceptions { get; set; }
        public virtual DbSet<ExceptionGroup> ExceptionGroups { get; set; }
        public virtual DbSet<ExceptionQueueLog> ExceptionQueueLogs { get; set; }
        public virtual DbSet<ExceptionType> ExceptionTypes { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
        public virtual DbSet<MessageLog> MessageLogs { get; set; }
    }
}
