//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.FastDataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class FASTProgramType
    {
        public int FASTProgramTypeId { get; set; }
        public int RegionId { get; set; }
        public string ProgramTypeName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int LastModifiedById { get; set; }
    }
}
