//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.Data.TerminalDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRegistration
    {
        public int CustomerRegistrationId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string PhoneNo { get; set; }
        public string CompanyName { get; set; }
        public string ProjectName { get; set; }
        public Nullable<bool> TitleAndSettlement { get; set; }
        public Nullable<bool> IneractiveOfficeDirectory { get; set; }
        public string Comments { get; set; }
        public Nullable<int> CustomerStatusId { get; set; }
        public Nullable<int> CreatedId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<bool> Other { get; set; }
        public string OtherRequirement { get; set; }
    
        public virtual TypeCode TypeCode { get; set; }
    }
}
