//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.Data.TerminalDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentObjectNodeLookUp
    {
        public int Id { get; set; }
        public string XMLHeader { get; set; }
        public string ExternalRefNumber { get; set; }
        public string CustomerRefNumber { get; set; }
        public string InternalRefNumber { get; set; }
        public string InternalRefId { get; set; }
        public string Source { get; set; }
        public string LocationExternalId { get; set; }
        public string LocationId { get; set; }
        public string ProviderExternalId { get; set; }
        public string ProviderId { get; set; }
        public string ServiceId { get; set; }
        public string ServiceRequestId { get; set; }
        public string PartyType { get; set; }
        public string BuyerFirstName { get; set; }
        public string BuyerLastName { get; set; }
        public string TransactionType { get; set; }
        public string ProgramTypeName { get; set; }
        public string ExternalApplicationId { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public string MessageType { get; set; }
        public string DocumentName { get; set; }
        public string GMTOffSet { get; set; }
        public string OrderDate { get; set; }
        public string EscrowOfficeID { get; set; }
    }
}
