//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.Data.TerminalDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FASTPreferenceMap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FASTPreferenceMap()
        {
            this.LoanConditions = new HashSet<LoanCondition>();
            this.LocationConditions = new HashSet<LocationCondition>();
            this.FASTPreferenceBusinessPrograms = new HashSet<FASTPreferenceBusinessProgram>();
            this.FASTPreferenceProducts = new HashSet<FASTPreferenceProduct>();
            this.ProductConditions = new HashSet<ProductCondition>();
        }
    
        public int FASTPreferenceMapId { get; set; }
        public string FASTPreferenceMapName { get; set; }
        public int FASTProgramTypeId { get; set; }
        public Nullable<int> FASTSearchTypeId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> LoanPurposeTypeCodeId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateById { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int LastModifiedById { get; set; }
        public int TenantId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual FASTProgramType FASTProgramType { get; set; }
        public virtual FASTSearchType FASTSearchType { get; set; }
        public virtual Location Location { get; set; }
        public virtual Service Service { get; set; }
        public virtual Tenant Tenant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanCondition> LoanConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationCondition> LocationConditions { get; set; }
        public virtual TypeCode TypeCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FASTPreferenceBusinessProgram> FASTPreferenceBusinessPrograms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FASTPreferenceProduct> FASTPreferenceProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCondition> ProductConditions { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
