//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.Data.TerminalDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FASTContactMap
    {
        public int FASTContactMapId { get; set; }
        public int ContactId { get; set; }
        public int FASTContactId { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
