//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.Data.TerminalDBEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TerminalLogEntities : DbContext
    {
        public TerminalLogEntities()
            : base("name=TerminalLogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Log> Logs { get; set; }
    
        public virtual ObjectResult<GetTermianlLog_Result> GetTermianlLog(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<bool> includeDebug, Nullable<bool> includeError, Nullable<bool> includeInfo, string searchText, Nullable<int> pageNumber, Nullable<int> maxCount)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            var includeDebugParameter = includeDebug.HasValue ?
                new ObjectParameter("includeDebug", includeDebug) :
                new ObjectParameter("includeDebug", typeof(bool));
    
            var includeErrorParameter = includeError.HasValue ?
                new ObjectParameter("includeError", includeError) :
                new ObjectParameter("includeError", typeof(bool));
    
            var includeInfoParameter = includeInfo.HasValue ?
                new ObjectParameter("includeInfo", includeInfo) :
                new ObjectParameter("includeInfo", typeof(bool));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("searchText", searchText) :
                new ObjectParameter("searchText", typeof(string));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            var maxCountParameter = maxCount.HasValue ?
                new ObjectParameter("maxCount", maxCount) :
                new ObjectParameter("maxCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTermianlLog_Result>("GetTermianlLog", startDateParameter, endDateParameter, includeDebugParameter, includeErrorParameter, includeInfoParameter, searchTextParameter, pageNumberParameter, maxCountParameter);
        }
    }
}
