//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.Data.TerminalDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitlePortLookUp
    {
        public int TitlePortLookupId { get; set; }
        public string ExternalRefNumber { get; set; }
        public string TagId { get; set; }
        public string TagSha1 { get; set; }
        public string TagData { get; set; }
        public string TagType { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string EventType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedById { get; set; }
        public string FileStatus { get; set; }
    }
}
