//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.Data.TerminalDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebHook
    {
        public string User { get; set; }
        public string Id { get; set; }
        public string ProtectedData { get; set; }
        public byte[] RowVer { get; set; }
        public Nullable<byte> MaxAttempts { get; set; }
    }
}
