//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.BEQResubmitProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentMap_Backup
    {
        public int DocumentMapId { get; set; }
        public string DocumentMapName { get; set; }
        public int DocumentTypeId { get; set; }
        public int ExternalDocTypeId { get; set; }
        public int ServiceId { get; set; }
        public bool IsInbound { get; set; }
        public string DocumentMapDesc { get; set; }
        public Nullable<int> StatusTypeCodeId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int LastModifiedById { get; set; }
        public int TenantId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    }
}
