//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.BEQResubmitProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exception
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exception()
        {
            this.ExceptionNotes = new HashSet<ExceptionNote>();
        }
    
        public int ExceptionId { get; set; }
        public int ExceptionTypeId { get; set; }
        public Nullable<int> MessageLogId { get; set; }
        public string ExceptionDesc { get; set; }
        public long DocumentObjectId { get; set; }
        public string Comments { get; set; }
        public int TypeCodeId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int LastModifiedById { get; set; }
    
        public virtual ExceptionType ExceptionType { get; set; }
        public virtual TypeCode TypeCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionNote> ExceptionNotes { get; set; }
    }
}
