//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.BEQResubmitProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FASTOffice
    {
        public int ID { get; set; }
        public int OfficeID { get; set; }
        public int RegionID { get; set; }
        public string OfficeName { get; set; }
        public string State { get; set; }
        public string County { get; set; }
    }
}
