//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.BEQResubmitProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FASTGABMap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FASTGABMap()
        {
            this.GABLocationConditions = new HashSet<GABLocationCondition>();
        }
    
        public int FASTGABMapId { get; set; }
        public int LocationId { get; set; }
        public int RegionId { get; set; }
        public string BusinessSourceABEID { get; set; }
        public string NewLenderABEID { get; set; }
        public Nullable<int> LoanTypeCodeId { get; set; }
        public string FASTGABMapDesc { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int LastModifiedById { get; set; }
        public string Notes { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual TypeCode TypeCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GABLocationCondition> GABLocationConditions { get; set; }
    }
}
