//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.BEQResubmitProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FASTPreferenceBusinessProgram
    {
        public int FASTPreferenceBusinessProgramId { get; set; }
        public int FASTPreferenceMapId { get; set; }
        public int FASTBusinessProgramTypeId { get; set; }
    
        public virtual FASTBusinessProgramType FASTBusinessProgramType { get; set; }
        public virtual FASTPreferenceMap FASTPreferenceMap { get; set; }
    }
}
