//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.Data.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionQueue
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string FastFileNumber { get; set; }
        public string IntegrationOrderID { get; set; }
        public string ClientOrderID { get; set; }
        public string LenderOrderID { get; set; }
        public string PropertyStreetAddress1 { get; set; }
        public string PropertyStreetAddress2 { get; set; }
        public string PropertyCity { get; set; }
        public string PropertyState { get; set; }
        public string PropertyZip { get; set; }
        public string Seller { get; set; }
        public string Lender { get; set; }
        public string Borrower { get; set; }
        public string EQDataXML { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string EQStatus { get; set; }
        public string EQCheckedOutTo { get; set; }
        public string ExceptionType { get; set; }
        public string EQNotes { get; set; }
        public string ServiceType { get; set; }
        public string TransactionType { get; set; }
        public string EQSourceNotes { get; set; }
        public string EQConnectorName { get; set; }
        public Nullable<int> TitleUID { get; set; }
        public Nullable<int> ClosingUID { get; set; }
        public int TitleMetadataID { get; set; }
        public int ClosingMetadataID { get; set; }
    }
}
