//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FA.LVIS.Tower.Data.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIPSCode
    {
        public string ZIPCode { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string CountyFIPS { get; set; }
        public string State { get; set; }
        public string StateCode { get; set; }
        public string StateFIPS { get; set; }
        public Nullable<double> MSA { get; set; }
        public Nullable<double> AreaCode { get; set; }
        public string TimeZone { get; set; }
        public Nullable<double> GMTOffset { get; set; }
        public string DST { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    }
}
